const FETCH_DATAS = 'FETCH_DATAS';
const FETCH_DATA = 'FETCH_DATA';
const DELETE_DATA = 'DELETE_DATA';
const CREATE_DATA = 'CREATE_DATA';
const EDIT_DATA = 'EDIT_DATA';
const FETCH_DATAS_FILTERED = 'FETCH_DATAS_FILTERED'
const FETCH_PASIEN_ID = 'FETCH_PASIEN_ID'

module.exports = {
  FETCH_DATAS,
  FETCH_DATA,
  DELETE_DATA,
  CREATE_DATA,
  EDIT_DATA,
  FETCH_DATAS_FILTERED,
  FETCH_PASIEN_ID
};
